# Ejercicio 1

Crear una lista de numeros secuenciales con valor minimo 10 y valor maximo 39. Convertir esta lista en una matriz de 3x10. Mostrar por pantalla el valor del numero que se encuentra en la esquina superior derecha.

In [1]:
import numpy as np

In [2]:
vector = np.arange(10,40)
matriz = vector.reshape(3,10)
matriz

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [3]:
matriz[0,9]

19

# Ejercicio 2

Crea un array de una dimension con 9 valores enteros entre el 0 y el 100. Convierte ese array en una matriz de dos dimensiones. Mostrar por pantalla el elemento de la esquina inferior derecha.

In [4]:
lista = np.random.randint(0, 100, 9)
lista

array([ 5, 52, 27, 55, 63, 77, 31, 22, 47])

In [5]:
matriz = lista.reshape(3,3)

In [6]:
matriz

array([[ 5, 52, 27],
       [55, 63, 77],
       [31, 22, 47]])

In [7]:
matriz[2,2]

47