## Numpy

- Vectores: Array de una unica dimension, es decir, una fila
- Matriz: Array de 2 dimensiones, 1 o mas filas y 1 o mas columnas

# Arrays

In [7]:
import numpy as np

# Vector (una dimension)

- Creo un array a partir de una lista de elementos

In [8]:
lista = [1, 2, 3, 4]

array = np.array(lista)
array

array([1, 2, 3, 4])

# Matriz (dos dimensiones)

In [9]:
lista2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

array2 = np.array(lista2)
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Funciones de numpy

# Arange

In [10]:
arr = np.arange(5)

Esto va a crear un arreglo compuesto de enteros del 0 al 4

In [11]:
arr

array([0, 1, 2, 3, 4])

Si le paso dos parametros, le digo inicio y fin-1 al array generado con arange

In [12]:
arr_limitado = np.arange(2, 10)
arr_limitado

array([2, 3, 4, 5, 6, 7, 8, 9])

Si le paso un 3er parametro, le estoy indicando el paso

In [13]:
arr_limitado_step = np.arange(0, 11, 2)
arr_limitado_step

array([ 0,  2,  4,  6,  8, 10])

# Zeros

- Nos permite generar un vector con la cantidad de cros que le pasemos como parametro

In [14]:
np.zeros(3)

array([0., 0., 0.])

- Si quiero que tenga 2 dimensiones, le paso (filas, columnas)

In [15]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

# Ones

- Funciona como zeros pero con unos

In [16]:
np.ones(3)

array([1., 1., 1.])

In [17]:
np.ones((2, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# Linspace

- Lo que hace esta funcion es generar un arreglo de n elementos con un limite inferior y uno superior
- Params --> (inicio, fin, n)

In [18]:
np.linspace(2, 8, 20)

array([2.        , 2.31578947, 2.63157895, 2.94736842, 3.26315789,
       3.57894737, 3.89473684, 4.21052632, 4.52631579, 4.84210526,
       5.15789474, 5.47368421, 5.78947368, 6.10526316, 6.42105263,
       6.73684211, 7.05263158, 7.36842105, 7.68421053, 8.        ])

# Eye

- Genera una matriz cuadrada con la cantidad de filas y columnas que le pasemos en el unico parametro. Es una matriz identidad.

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Numeros Aleatorios

# Rand

- Esta funcion genera un vector de n numeros aleatorios o una matriz si le pasamos ambos parametros
- Va a tener tantas dimensiones como parametros yo le pase
- Distribucion uniforme de los numeros

- Vector

In [20]:
np.random.rand(5)

array([0.02646731, 0.97343892, 0.20728965, 0.6555535 , 0.59567423])

- Matriz

In [21]:
np.random.rand(5,6)

array([[0.12543171, 0.91635408, 0.12024893, 0.06576626, 0.23520773,
        0.54307238],
       [0.86529675, 0.83202595, 0.26178474, 0.15670874, 0.8093257 ,
        0.06183658],
       [0.68548525, 0.74274376, 0.27455637, 0.67093213, 0.48914673,
        0.15978909],
       [0.5462883 , 0.69344655, 0.56106846, 0.61183393, 0.73712821,
        0.42284845],
       [0.83157559, 0.66289174, 0.0171817 , 0.49557544, 0.52198076,
        0.9757067 ]])

# Randn

- Genera n elementos con distribucion normal
- La cantidad de parametros indica la cantidad de dimensiones

In [22]:
np.random.randn(5)

array([-0.83274511,  0.70033522, -0.67743911, -0.2880391 , -0.52697896])

In [23]:
np.random.randn(3,4)

array([[ 1.46236192, -2.18875472,  0.95870623, -2.87232896],
       [-0.36642421,  0.05217462, -0.2910749 , -1.4071324 ],
       [-0.63326589,  0.92683209,  0.6022337 ,  0.79644564]])

# Randint
- Numeros aleatorios enteros

In [24]:
np.random.randint(1,20)

18

- Para generar mas de un numero aleatorio, agrego un parametro y me queda (inicio, fin-1, n)

In [25]:
np.random.randint(1,20,4)

array([17, 17,  9,  9])

# Cambio de tamaño - Reshape

- Ejemplo: quiero pasar de un vector a una matriz, uso la funcion reshape siempre y cuando m.filas * m.cols = len(vector)
- arr.reshape(filas, columnas)

In [29]:
arr = np.random.randint(1, 100, 21)
arr

array([ 9, 53, 90, 22, 34, 21, 25, 84, 64, 20, 91, 37, 43, 47,  9, 83, 79,
       80, 11, 80,  2])

In [30]:
matriz = arr.reshape(7,3)
matriz

array([[ 9, 53, 90],
       [22, 34, 21],
       [25, 84, 64],
       [20, 91, 37],
       [43, 47,  9],
       [83, 79, 80],
       [11, 80,  2]])

# Valores minimos y maximos

In [31]:
arr = np.random.randint(1,100,50)
arr

array([48, 71, 67, 67, 28, 88, 44, 59, 59, 38, 57,  4, 42,  3, 19, 87, 37,
       77, 19, 77, 89, 98, 65, 46,  1, 14, 33, 11, 58, 66, 53, 96, 29, 55,
       72, 35, 91, 85, 25, 10,  4, 33, 51, 24, 44, 72, 84, 18, 15, 82])

- Valor Maximo

In [32]:
max_value = arr.max()
max_value

98

Para saber en que posicion del arreglo esta el valor maximo

In [34]:
max_value_arg = arr.argmax()
max_value_arg

21

- Valor minimo

In [35]:
min_value = arr.min()
min_value

1

Para saber la posicion del valor minimo

In [36]:
min_value_arg = arr.argmin()
min_value_arg

24

# Indexacion en Arrays de una dimension

- Acceso a las posiciones especificas del array
- Array [n]

In [39]:
array = np.arange(0,10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
array[0]

0

In [41]:
array[-1]

9

- Para acceder a varios [inicio:fin-1]

In [42]:
array[2:4]

array([2, 3])

- Todo el array [:]

In [43]:
array[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- De una posicion al final [n:]
- Del inicio a una posicion [:n]

In [44]:
array[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
array[:4]

array([0, 1, 2, 3])

- Copiar un array --> array.copy()

- Modificar el valor en una posicion n --> arr[n] = valor

# Indexaion en Arrays de dos dimensiones

In [46]:
arr2 = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

- [filas] [columnas]
- Si pongo solo un [] traigo todas las columnas de las filas que pida


In [47]:
arr2[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
arr2[2]

array([7, 8, 9])

In [49]:
arr2[:2]

array([[1, 2, 3],
       [4, 5, 6]])

- Si pongo [n][m] me va a traer el elemento que se encuentre en la fila n y columna m.
- O directamente [n, m]

In [54]:
arr2[1][1]

5

In [55]:
arr2[1,1]

5

- Todas las formas que funcionaban en el array de una dimension las puedo aplicar aca tanto en filas como en columnas

# Seleccionando segun una condicion

In [56]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

- Si testeo la condicion directamente, me va a devolver una lista de booleanos siendo True el valor si ese elemento la cumple y False de lo contrario.

In [57]:
condicion = arr > 5
condicion

array([False, False, False, False, False, False,  True,  True,  True,
        True])

- Si quiero devolver una lista con los valores que cumplan con la condicion

In [59]:
arr[condicion]

array([6, 7, 8, 9])

In [60]:
arr[arr % 2 == 0]

array([0, 2, 4, 6, 8])

# Operaciones con Arrays

- Podemos realizar operaciones directamente sobre dos arrays y va a iterar la operacion sobre cada elemento.
- Para poder operar con dos arrays deben tener el mismo tamaño
- arr viene ya de las celdas anteriores, si tira error, correr el In[56]

In [62]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [63]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [64]:
arr * 100

array([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

- Tambien hay funciones que podemos aplicar sobre cada elemento del array, como por ejemplo la raiz cuadrada

In [69]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [70]:
np.max(arr)

9

In [71]:
np.min(arr)

0

- Con np. TAB puedo ver la serie de funciones que le puedo aplicar al array --> np.func(arr)