## Numpy

- Vectores: Array de una unica dimension, es decir, una fila
- Matriz: Array de 2 dimensiones, 1 o mas filas y 1 o mas columnas

# Arrays

In [7]:
import numpy as np

# Vector (una dimension)

- Creo un array a partir de una lista de elementos

In [5]:
lista = [1, 2, 3, 4]

array = np.array(lista)
array

array([1, 2, 3, 4])

# Matriz (dos dimensiones)

In [8]:
lista2 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

array2 = np.array(lista2)
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Funciones de numpy

# Arange

In [10]:
arr = np.arange(5)

Esto va a crear un arreglo compuesto de enteros del 0 al 4

In [11]:
arr

array([0, 1, 2, 3, 4])

Si le paso dos parametros, le digo inicio y fin-1 al array generado con arange

In [12]:
arr_limitado = np.arange(2, 10)
arr_limitado

array([2, 3, 4, 5, 6, 7, 8, 9])

Si le paso un 3er parametro, le estoy indicando el paso

In [13]:
arr_limitado_step = np.arange(0, 11, 2)
arr_limitado_step

array([ 0,  2,  4,  6,  8, 10])

# Zeros

- Nos permite generar un vector con la cantidad de cros que le pasemos como parametro

In [14]:
np.zeros(3)

array([0., 0., 0.])

- Si quiero que tenga 2 dimensiones, le paso (filas, columnas)

In [15]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

# Ones

- Funciona como zeros pero con unos

In [16]:
np.ones(3)

array([1., 1., 1.])

In [17]:
np.ones((2, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# Linspace

- Lo que hace esta funcion es generar un arreglo de n elementos con un limite inferior y uno superior
- Params --> (inicio, fin, n)

In [19]:
np.linspace(2, 8, 20)

array([2.        , 2.31578947, 2.63157895, 2.94736842, 3.26315789,
       3.57894737, 3.89473684, 4.21052632, 4.52631579, 4.84210526,
       5.15789474, 5.47368421, 5.78947368, 6.10526316, 6.42105263,
       6.73684211, 7.05263158, 7.36842105, 7.68421053, 8.        ])

# Eye

- Genera una matriz cuadrada con la cantidad de filas y columnas que le pasemos en el unico parametro. Es una matriz identidad.

In [21]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Numeros Aleatorios

# Rand

- Esta funcion genera un vector de n numeros aleatorios o una matriz si le pasamos ambos parametros
- Va a tener tantas dimensiones como parametros yo le pase
- Distribucion uniforme de los numeros

- Vector

In [24]:
np.random.rand(5)

array([0.68092402, 0.27724246, 0.49973193, 0.7756434 , 0.08987881])

- Matriz

In [26]:
np.random.rand(5,6)

array([[0.30808456, 0.42651767, 0.05023213, 0.45638863, 0.80180373,
        0.14167939],
       [0.49871188, 0.35310258, 0.43330123, 0.7512775 , 0.47885871,
        0.67677171],
       [0.09030552, 0.83716278, 0.90519392, 0.11501625, 0.40495048,
        0.69397188],
       [0.18256521, 0.40884852, 0.72088827, 0.83032479, 0.99967534,
        0.36660755],
       [0.701441  , 0.81523005, 0.53053678, 0.06623537, 0.21383744,
        0.97029352]])

# Randn

- Genera n elementos con distribucion normal
- La cantidad de parametros indica la cantidad de dimensiones

In [27]:
np.random.randn(5)

array([-1.77602867, -1.86389533, -2.15575535,  0.51081542,  0.77681568])

In [28]:
np.random.randn(3,4)

array([[-1.11222071, -0.49352248,  0.04377233, -0.30212387],
       [-0.38643333,  2.10545816,  0.57506639,  0.00325222],
       [ 0.42293803, -0.99418565,  0.37364436, -0.68319499]])

# Randint
- Numeros aleatorios enteros

In [29]:
np.random.randint(1,20)

9

- Para generar mas de un numero aleatorio, agrego un parametro y me queda (inicio, fin-1, n)

In [30]:
np.random.randint(1,20,4)

array([16,  5,  5,  1])

# Cambio de tamaño - Reshape

- Ejemplo: quiero pasar de un vector a una matriz, uso la funcion reshape siempre y cuando m.filas * m.cols = len(vector)
- arr.reshape(filas, columnas)

In [32]:
arr = np.random.randint(1, 100, 25)
arr

array([85, 40, 36, 28, 42, 59, 28, 34, 95, 28, 40, 24, 48, 11, 59, 32, 94,
       24, 33, 16, 24, 82, 13, 88, 85])

In [ ]:
matriz = 